.TH GIT-lables 1 "April 2025" "git-lables 1.0" "Git Manual"
.SH NAME
git-lables \- List Git lables from a repository
.SH SYNOPSIS
.B git lables
\fI<repo-name>\fR
.SH DESCRIPTION
\fBgit-lables\fR fetches and displays Git lables from a specified repository.
.SH OPTIONS
.TP
\fI<repo-name>\fR
Specify the repository to fetch lables from. This can be a local path (e.g., ".") or a remote repository URL.
.TP
\fB\-\-help\fR
Display help information.
.SH EXAMPLES
.TP
List lables from the current repository:
\fBgit lables .\fR
.TP
List lables from a remote repository:
\fBgit lables https://github.com/user/repo.git\fR
.SH SEE ALSO
\fBgit-who\fR(1)